// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "./lib/types.sol";
import { SkyNftUtils } from "./lib/utils.sol";
import { Strings } from "@openzeppelin/contracts/utils/Strings.sol";

library SkyNftSvgStarNames {
    using Strings for int16;

    function getCode(SkyMap calldata skymap) public pure returns (string memory code) {
        bytes24[237] memory starNames = [
            bytes24("Alpheratz"),
            "Caph",
            "Algenib",
            "Ankaa",
            "Schedar",
            "Deneb Kaitos",
            "Mirach",
            "Adhil",
            "Ruchbah",
            "Achernar",
            "Baten Kaitos",
            "Mothallah",
            "Mesartim",
            "Sheratan",
            "Alrescha",
            "Almach",
            "Hamal",
            "Mira",
            "Polaris",
            "Azha",
            "Acamar",
            "Menkar",
            "Algol",
            "Botein",
            "Zibal",
            "Mirfak",
            "Atik",
            "Celaeno",
            "Electra",
            "Taygeta",
            "Maia",
            "Sterope",
            "Merope",
            "Alcyone",
            "Atlas",
            "Pleione",
            "Zaurak",
            "Menkib",
            "Beid",
            "Keid",
            "Theemin",
            "Ain",
            "Aldebaran",
            "Hind's Crimson Star",
            "Cursa",
            "Rigel",
            "Capella",
            "Bellatrix",
            "Elnath",
            "Nihal",
            "Mintaka",
            "Arneb",
            "Meissa",
            "Alnilam",
            "Phact",
            "Alnitak",
            "Saiph",
            "Wazn",
            "Betelgeuse",
            "Menkalinan",
            "Propus",
            "Furud",
            "Mirzam",
            "Tejat",
            "Canopus",
            "Alhena",
            "Mebsuta",
            "Sirius",
            "Adhara",
            "Muliphein",
            "Mekbuda",
            "Wezen",
            "Wasat",
            "Aludra",
            "Gomeisa",
            "Castor",
            "Procyon",
            "Pollux",
            "Naos",
            "Tureis",
            "Regor",
            "Tegmine",
            "Avior",
            "Muscida",
            "Asellus Borealis",
            "Asellus Australis",
            "Acubens",
            "Talitha",
            "Vela X-1",
            "Suhail",
            "Miaplacidus",
            "Aspidiske",
            "Markeb",
            "Alphard",
            "Alterf",
            "Subra",
            "Rasalas",
            "Regulus",
            "Adhafera",
            "Tania Borealis",
            "Algieba",
            "Tania Australis",
            "Alkes",
            "Merak",
            "Lalande 21185",
            "Dubhe",
            "Zosma",
            "Chertan",
            "Alula Australis",
            "Alula Borealis",
            "Giausar",
            "Denebola",
            "Zavijava",
            "Groombridge 1830",
            "Phecda",
            "Alchiba",
            "Rmk 14",
            "Megrez",
            "Gienah",
            "Zaniah",
            "Acrux",
            "Algorab",
            "Gacrux",
            "Chara",
            "Muhlifain",
            "Porrima",
            "Mimosa",
            "Alioth",
            "Cor Caroli",
            "Vindemiatrix",
            "Mizar",
            "Spica",
            "Alcor",
            "Alkaid",
            "Muphrid",
            "Alnair",
            "Hadar",
            "Thuban",
            "Menkent",
            "Arcturus",
            "Syrma",
            "V1002",
            "Proxima Centauri",
            "Seginus",
            "Rigil Kentaurus",
            "Izar",
            "Merga",
            "Kochab",
            "Zubenelgenubi",
            "H N 28",
            "Nekkar",
            "Zubeneschamali",
            "Pherkad",
            "Alkalurops",
            "Edasich",
            "Nusakan",
            "Alphecca",
            "Unukalhai",
            "T = Blaze Star",
            "Dschubba",
            "Graffias",
            "Marsic",
            "Yed Prior",
            "Yed Posterior",
            "Al Niyat",
            "Cujam",
            "Antares",
            "Kornephoros",
            "Marfik",
            "Atria",
            "Alrakis",
            "Sabik",
            "Rasalgethi",
            "Rastaban",
            "Maasym",
            "Lesath",
            "Yildun",
            "Shaula",
            "Rasalhague",
            "Girtab",
            "Cebalrai",
            "Grumium",
            "Eltanin",
            "Barnard's Star",
            "Alnasl",
            "Kaus Media",
            "Kaus Australis",
            "Kaus Borealis",
            "Vega",
            "Sheliak",
            "Nunki",
            "Alya",
            "Sulafat",
            "Ascella",
            "Altais",
            "Arkab",
            "Rukbat",
            "Albireo",
            "Sham",
            "Tarazed",
            "Altair",
            "Alshain",
            "Algedi",
            "Dabih",
            "Sadr",
            "Peacock",
            "Rotanev",
            "Sualocin",
            "Deneb",
            "Albali",
            "Kitalpha",
            "Lacaille 8760",
            "Alderamin",
            "Alfirk",
            "Sadalsuud",
            "Nashira",
            "Azelfafage",
            "Herschel's Garnet Star",
            "Enif",
            "Deneb Algedi",
            "Kurhah",
            "Sadalmelik",
            "Al Na'ir",
            "Biham",
            "Ancha",
            "Sadachbia",
            "Krueger 60",
            "Situla",
            "Homam",
            "Matar",
            "Sadalbari",
            "Skat",
            "Fomalhaut",
            "Scheat",
            "Markab",
            "Bradley 3077",
            "Errai"
        ];
        uint256 namedStarIdx = 0;
        for (uint8 i = 0; i < starNames.length; i++) {
            if (!SkyNftUtils.isBitSet(skymap.namedStarsBitMap, i)) continue;
            uint24 coords = skymap.starsCoords[skymap.namedStarsCoordsIndexes[namedStarIdx]];
            (int16 x, int16 y) = SkyNftUtils.unpackCoords(coords);
            string memory xStr = x.toStringSigned();
            string memory yStr = y.toStringSigned();
            code = string.concat(
                code,
                '<g class="s1"><use href="#s1" x="',
                xStr,
                '" y="',
                yStr,
                '"/>'
                '<text x="',
                xStr,
                '" y="',
                yStr,
                '">',
                SkyNftUtils.bytesToString(starNames[i]),
                "</text></g>"
            );
            namedStarIdx++;
        }
        return code;
    }
}
