version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: skynftapi:${SKYNFTAPI_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      SKYNFTAPI_HOST: 0.0.0.0
