name: Build and Publish Api Docker Image to GitHub Registry

on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Lowercase Repo Name
      id: lowercase-repo-name
      run: echo "REPO_NAME_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: packages/api
        file: packages/api/deploy/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_NAME_LOWERCASE }}/skynftapi:${{ github.sha }}

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
